"""Add visible_in_user_response field to Param table

Revision ID: ea9459426db1
Revises: f8c57101c0f6
Create Date: 2024-05-12 20:27:45.549332

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'ea9459426db1'
down_revision = 'f8c57101c0f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('param', sa.Column('visible_in_user_response', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('param', 'visible_in_user_response')
    # ### end Alembic commands ###
