"""add_is_public_field_to_param

Revision ID: fc911d58459b
Revises: 5a6490c55c81
Create Date: 2025-03-11 21:38:50.699014

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'fc911d58459b'
down_revision = '5a6490c55c81'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('param', sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.false()))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('param', 'is_public')
    # ### end Alembic commands ###
